version: 1.0.{build}
os: Visual Studio 2015
clone_folder: C:\projects\pybind11
test: off
configuration:
    - Release
    - Debug
branches:
  only:
    - master
environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python34"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python34-x64"
install:
  - cinstall: python
build_script:
  - echo Running cmake...
  - cd c:\projects\pybind11
  - cmake -G "%CMAKE_PLATFORM%" -DPYTHON_INCLUDE_DIR:PATH=%PYTHON_DIR%/include -DPYTHON_LIBRARY:FILEPATH=%PYTHON_DIR%/libs/python34.lib -DPYTHON_EXECUTABLE:FILEPATH=%PYTHON_DIR%/python.exe
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%Configuration% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% pybind11.sln
  - ctest -C %Configuration%
