package:
  name: pybind11
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - pybind11

about:
  home: https://github.com/pybind/pybind11/
  summary: Seamless operability between C++11 and Python
